# Generated by Django 4.0.1 on 2022-01-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='设备名')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('platform', models.CharField(max_length=128, verbose_name='设备类型')),
                ('group', models.CharField(max_length=128, verbose_name='所属组')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('port', models.CharField(default=22, max_length=128, verbose_name='端口号')),
            ],
        ),
        migrations.CreateModel(
            name='Oxidized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='设备名')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('platform', models.CharField(max_length=128, verbose_name='设备类型')),
                ('group', models.CharField(max_length=128, verbose_name='所属组')),
                ('state', models.BooleanField(default=False, max_length=128, verbose_name='最后一次采集的状态')),
                ('last_update', models.DateTimeField(max_length=128, verbose_name='最后一次更新的时间')),
                ('last_change', models.DateTimeField(max_length=128, verbose_name='最后一次更改的时间')),
                ('config', models.TextField(max_length=128, verbose_name='配置信息')),
                ('diff', models.TextField(default='null', max_length=128, verbose_name='差异信息')),
            ],
        ),
    ]
