# Generated by Django 4.0.1 on 2022-01-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxidized', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxidized',
            name='last_change',
            field=models.DateTimeField(auto_now=True, max_length=128, verbose_name='最后一次更改的时间'),
        ),
        migrations.AlterField(
            model_name='oxidized',
            name='last_update',
            field=models.DateTimeField(auto_now=True, max_length=128, verbose_name='最后一次更新的时间'),
        ),
    ]
