# Generated by Django 4.0.1 on 2022-01-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxidized', '0002_alter_oxidized_last_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxidized',
            name='last_change',
            field=models.DateTimeField(max_length=128, verbose_name='最后一次更改的时间'),
        ),
    ]
